run:
	go run cmd/shumnaya/main.go

seede:
	go run cmd/seed/main.go

fmt:
	go fmt ./...

vet:
	go vet ./...

tidy:
	go mod tidy

test:
	go test -v ./...
# Запуск тестов с покрытием
test-cover:
	go test -cover ./...
# Генерация HTML-отчёта о покрытии
cover-html:
	go test -coverprofile=coverage.out ./...
	go tool cover -html=coverage.out

lint:
	golangci-lint run

dev:
	air

build:
	go build -o shumnaya cmd/shumnaya/main.go

swagger:
	cd cmd/shumnaya && swag init -g main.go -o ../../docs -d .,../../internal --parseDependency --parseInternal

