run:
	go run cmd/shumnaya/main.go

seede:
	go run cmd/seed/main.go

fmt:
	go fmt ./...

vet:
	go vet ./...

tidy:
	go mod tidy

lint:
	golangci-lint run

dev:
	air

build:
	go build -o shumnaya cmd/shumnaya/main.go